### ISSUE TITLE
global music PCA

### ISSUE THREAD

**Issue by goertzenlr** [TheEconomist/graphic-detail-data#10]
Would be interested to know how PCA was run, i.e. labels for tracks (genre etc) included as well as track itself.  Great feature.

**Comment by dsett** [comment]
The PCA analysis incorporated top lyrics languages, artists, tracks, artist nationalities, and genres for each country. Sources for artist nationalities were Soundcharts, Popnable and Google searches, and the source for genres was Soundcharts.
